name: Publish MSFT ASN IP Ranges
permissions: write-all

# This workflow will run once a day at 12 or on push or pull request events but only for the "master" branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron:  '0 12 * * *'

  # Allows this workflow to run manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      # Checks-out this repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      
      # Runs get_msft_ips.ps1 with PS
      - name: Run get_msft_ips Script
        shell: pwsh
        run: ./get_msft_ips.ps1
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}-${{ github.GITHUB_REPOSITORY }}
          release_name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          
      - name: Build Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./msft_asn_ip_ranges.txt
          asset_name: msft_asn_ip_ranges.txt
          asset_content_type: text/plain
      - name: Remove Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          removeArtifacts: "Source code.zip"
